# Generated by Django 5.1.3 on 2024-11-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carposition', '0003_auto_20181103_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
