# Generated by Django 5.1.3 on 2024-11-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_auto_20190409_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
